setup.py

As Dash itself is currently on version `0.x.x` there are regulary breaking changes. To make life easier for `webviz` we freeze Dash version and instead update in designated pull requests.

Freeze dash packages

---

webviz_config/static/assets/webviz_layout.css
webviz_config/themes/default_assets/default_theme.css

Fixed layout issue when front page is the only page

---

webviz_config/common_cache.py

Increased cache to 1 hour

---

webviz_config/containers/_markdown.py

Make Markdown portable

---

webviz_config/_config_parser.py

Load custom containers from correct module

---

webviz_config/static/Dockerfile

Change `chown` according to https://github.com/equinor/webviz-docker/pull/7

Update chown argument in Dockerfile

---

setup.py
tests/data/basic_example.yaml
tests/test_syntax_highlighter.py
webviz_config/containers/_syntax_highlighter.py

Use Markdown component for syntax highlighting

---

examples/basic_example.yaml
tests/data/basic_example.yaml
tests/test_table_plotter.py
webviz_config/containers/_table_plotter.py

Remove title argument

---

CONTRIBUTING.md
examples/basic_example.yaml
setup.py
webviz_config/_config_parser.py
webviz_config/containers/__init__.py
webviz_config/containers/_banner_image.py
webviz_config/containers/_container_class.py
webviz_config/containers/_example_data_download.py
webviz_config/containers/_table_plotter.py
webviz_config/templates/webviz_template.py.jinja2

Resolves #37 and resolves #69.

Use webviz container component

---

webviz_config/_config_parser.py
webviz_config/templates/copy_data_template.py.jinja2
webviz_config/templates/webviz_template.py.jinja2

Fix webviz store

---

.travis.yml
README.md
setup.py
tests/test_portable.py

Add test for portable app

---

examples/basic_example.yaml
tests/test_table_plotter.py
webviz_config/containers/_table_plotter.py

Added filtering option to the TablePlotter.
The filter is activated by adding the argument `filter_cols` to the config files, and specifying a list of dataframe columns that are filterable.
For numerical columns a RangeSlider is rendered. For other datatypes a dropdown is rendered.

Added data filtering to TablePlotter

---

examples/basic_example.yaml
webviz_config/containers/_container_class.py

Contact person data as string

---

webviz_config/_build_webviz.py
webviz_config/webviz_assets.py
webviz_config/webviz_store.py

Add progress information when making portable webviz

---

webviz_config/_build_webviz.py
webviz_config/_certificate.py
webviz_config/_config_parser.py
webviz_config/_localhost_open_browser.py
webviz_config/utils/terminal_colors.py
webviz_config/webviz_assets.py
webviz_config/webviz_store.py

Resolves #103.
Ran `grep -rnw . -e '033'` on the code base to ensure there are no remaining ANSI sequences not "outsourced" to `terminal_colors`.

Collect ANSI sequences

---

webviz_config/_certificate.py
webviz_config/command_line.py

- Add automatic installation option (given that `certutil` is available).
- Resolves #89.

Add installation option for certificate

---

webviz_config/_localhost_open_browser.py
webviz_config/templates/webviz_template.py.jinja2

Some users have quite arcane default browser. Try to open `chrome` or `chromium` before using system default.

Add preferred browser to auto-open in

---

examples/basic_example.yaml
setup.py
tests/test_portable.py
webviz_config/_container_abc.py
webviz_config/containers/__init__.py
webviz_config/containers/_example_tour.py

This is the `webviz-config` part of https://github.com/equinor/webviz-core-components/pull/24.

Add guided tour

---

webviz_config/_build_webviz.py
webviz_config/_localhost_open_browser.py
webviz_config/_localhost_token.py
webviz_config/_write_script.py
webviz_config/command_line.py
webviz_config/templates/webviz_template.py.jinja2
webviz_config/utils/__init__.py
webviz_config/utils/_available_port.py
webviz_config/utils/_silence_flask_startup.py

- Find and choose available port automatically. Resolves #116.
- Hide confusing output from flask startup. Resolves #115.

Find available port + remove confusing flask output

---

tests/test_portable.py

Solve import-outside-toplevel

---

.travis.yml

Update Chromedriver on Travis

---

examples/basic_example.yaml
webviz_config/_config_parser.py

Warn user on tabs in configuration file

---

webviz_config/containers/_banner_image.py
webviz_config/static/assets/webviz_config.css

Add height as optional parameter to banner image

---

.pylintrc
webviz_config/__init__.py
webviz_config/_localhost_certificate.py
webviz_config/_write_script.py
webviz_config/templates/webviz_template.py.jinja2

Create localhost cert on the fly

---

webviz_config/templates/webviz_template.py.jinja2

Faster startup time localhost

---

webviz_config/templates/copy_data_template.py.jinja2
webviz_config/templates/webviz_template.py.jinja2

Black template

---

webviz_config/templates/copy_data_template.py.jinja2

Added plotly layout to copy_template

---

webviz_config/templates/webviz_template.py.jinja2

Add temporary dash table workaround

---

webviz_config/_config_parser.py

Resolve path to lists of pathlib objects

---

CONTRIBUTING.md
webviz_config/_shared_settings_subscriptions.py
webviz_config/templates/copy_data_template.py.jinja2
webviz_config/templates/webviz_template.py.jinja2

Related to https://github.com/equinor/webviz-subsurface/pull/164.

Add optional portable information to subscription

---

webviz_config/_build_webviz.py
webviz_config/_theme_class.py
webviz_config/_write_script.py
webviz_config/templates/copy_data_template.py.jinja2
webviz_config/templates/webviz_template.py.jinja2

theme to/from json

---

webviz_config/_theme_class.py

frame-src csp self

---

tests/test_example_plugin.py
tests/test_table_plotter.py
webviz_config/_plugin_abc.py
webviz_config/plugins/_data_table.py
webviz_config/plugins/_example_plugin.py
webviz_config/plugins/_example_tour.py
webviz_config/plugins/_table_plotter.py

uuid method

---

setup.py
tests/test_table_plotter.py
webviz_config/plugins/_table_plotter.py

GIve table plotter a responsive layout using `wcc.FlexBox`.

Use wcc.FlexBox

---

webviz_config/_write_script.py
webviz_config/command_line.py
webviz_config/templates/copy_data_template.py.jinja2
webviz_config/templates/webviz_template.py.jinja2

Command line option for log level

---

webviz_config/_build_webviz.py
webviz_config/static/README.md
webviz_config/templates/copy_data_template.py.jinja2
webviz_config/templates/webviz_template.py.jinja2

Support Windows

---

LICENSE
README.md
setup.py

Change to MIT license

---

tests/test_create_themed_layout.py
webviz_config/_theme_class.py

Deep update plotly layout

---

webviz_config/plugins/_syntax_highlighter.py

Add newlines to syntax highlighter code block

---

examples/example-markdown.md
setup.py
webviz_config/plugins/_markdown.py

Workaround for https://github.com/plotly/dash-core-components/issues/746.

Resolve upstream issue with void tags in Dash Markdown

---

.github/workflows/webviz-config.yml

Latest astroid/pylint combo fails with Pandas 2.4.2.
https://github.com/PyCQA/astroid/issues/773.

Do not check code style using pandas version < 1.0

---

examples/basic_example.yaml
webviz_config/plugins/_table_plotter.py

Resolves #237 
**Additionally**: Ignores non-numeric dimensions (columns) for parallel coordinates.

Filter defaults, barmode for barcharts and specified colormap

---

webviz_config/templates/webviz_template.py.jinja2
webviz_config/utils/_available_port.py

Semi-deterministic port in order to use persistence

---

.github/workflows/webviz-config.yml

Deploy GitHub pages on releases only

---

setup.py
webviz_config/webviz_assets.py
webviz_config/webviz_store.py

Reduces console output by _a lot_.

Progress bar for webviz store/assets

---

webviz_config/_build_webviz.py

Use sys.executable in subcalls

---

webviz_config/_plugin_abc.py

Alow plugin users to change the filename used when the screenshot is saved.

Change screenshot file name

---

webviz_config/_config_parser.py
webviz_config/_docs/_build_docs.py
webviz_config/_docs/_create_schema.py
webviz_config/_shared_settings_subscriptions.py
webviz_config/_user_data_dir.py
webviz_config/certificate/_localhost_certificate.py
webviz_config/command_line.py
webviz_config/plugins/_markdown.py
webviz_config/plugins/_table_plotter.py
webviz_config/utils/_localhost_open_browser.py
webviz_config/webviz_assets.py

Code style changes for new black version

---

.github/CODEOWNERS
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md
CHANGELOG.md

Add CHANGELOG, CODEOWNERS and issue/PR templates

---

webviz_config/static/assets/webviz_layout.css
webviz_config/templates/webviz_template.py.jinja2

Scrollable sidebar

---

CHANGELOG.md
CONTRIBUTING.md
setup.py
webviz_config/__init__.py
webviz_config/_plugin_abc.py
webviz_config/plugins/_example_data_download.py
webviz_config/plugins/_table_plotter.py

Support generic type of download file

---

webviz_config/_build_webviz.py
webviz_config/_config_parser.py
webviz_config/_docs/open_docs.py
webviz_config/_user_preferences.py
webviz_config/_write_script.py
webviz_config/certificate/_certificate_generator.py
webviz_config/certificate/_localhost_certificate.py
webviz_config/command_line.py
webviz_config/templates/copy_data_template.py.jinja2
webviz_config/templates/webviz_template.py.jinja2
webviz_config/themes/_default_theme.py
webviz_config/webviz_assets.py
webviz_config/webviz_store.py

Closes #196 
Bare with me on this one, first time using pathlib and still trying to get a full understanding of the repository 
Would appreciate some feedback from one of the maintainers to see I'm on the right track with the changes so far!

Consolidate usage of pathlib.Path instead of os.path

---

CHANGELOG.md
webviz_config/static/assets/webviz_layout.css
webviz_config/templates/webviz_template.py.jinja2

Specify menu width

---

CHANGELOG.md
webviz_config/webviz_store.py

Give RuntimeWarning if cached/stored functions use pandas object arguments

---

CHANGELOG.md

New release - update changelog.

Update changelog after new release

---

package-lock.json
package.json
webviz_config/_docs/_build_docs.py

Remove workaround, as bug fixed in latest release of `docsify-tabs`.

Update docsify-tabs dependency

---

.github/workflows/webviz-config.yml

Edit deprecated set-env in GitHub Actions workflow

---

.github/workflows/webviz-config.yml
CONTRIBUTING.md
setup.py

New pip resolver failed on pip install in CI

Don't use new pip resolver

---

.github/workflows/webviz-config.yml

Pin pandas to 1.1.4 due to bug with pylint in pandas 1.1.5

---

CHANGELOG.md

Updates `CHANGELOG.md` for release of `0.2.4`

Update CHANGELOG for release 0.2.4

---

CHANGELOG.md

Bumped version number in CHANGELOG to 0.2.7 in preparation for new release

Update changelog for release 0.2.7

---

CHANGELOG.md
webviz_config/utils/_localhost_open_browser.py

Prefer firefox over chrome to ease localhost certificate transition

---

CHANGELOG.md

Update CHANGELOG for version 0.2.8

---

.github/workflows/webviz-config.yml
README.md

Add Python 3.9 to CI

---

webviz_config/_build_webviz.py

Closes #424.
In addition to using context manager (removing new `pylint` suggestion) we also get rid of a couple of lines `process.wait()`, since the context manager takes care of this (https://docs.python.org/3/library/subprocess.html#popen-constructor):
> Added in Python 3.2: Context manager support. `Popen` objects are supported as context managers via the `with` statement: on exit, standard file descriptors are closed, **and the process is waited for.**

Use context manager with subprocess.Popen

---

CHANGELOG.md
webviz_config/generic_plugins/_markdown.py

Related to https://github.com/equinor/webviz-config-equinor/pull/39.

Add class name to Markdown plugin output

---

CHANGELOG.md
webviz_config/deprecation_decorators.py

mypy: Replaced `WebvizPluginABC` type with `Type[WebvizPluginABC]`

---

CHANGELOG.md
CONTRIBUTING.md
webviz_config/deprecation_decorators.py

Depending on #429 to be taken in first.

Removed `short_message` from `plugin_deprecated`

---

CHANGELOG.md
tests/test_docker_setup.py
webviz_config/_dockerize/_create_docker_setup.py

Support + test source_url/download_url combinations

---

webviz_config/_localhost_token.py
webviz_config/_oauth2.py
webviz_config/webviz_assets.py

Based on feedback from https://github.com/pallets/flask/issues/4020.
Closes #450.

Disable pylint warning on `flask.g` object, and fix `mypy` issues after type hinted `flask`

---

setup.py
tests/test_create_themed_layout.py
tests/test_data_table.py
tests/test_plugin_init.py
tests/test_syntax_highlighter.py

Use std.lib `mock`

---

CHANGELOG.md
webviz_config/_plugin_abc.py
webviz_config/templates/feedback.md.jinja2

Moved generation of deprecation warnings into separate private function and added private function for creating feedback URL. Also made a private function outside the class for creating the feedback body text from a Jinja2 template.
Depending on equinor/webviz-core-components#130 to be taken in first..

Added report feedback button to `WebvizPluginABC`

---

CHANGELOG.md
webviz_config/_deployment/radix.py
webviz_config/templates/radixconfig.yaml.jinja2

Use non-root `redis` image

---

CHANGELOG.md
webviz_config/templates/radixconfig.yaml.jinja2

See https://github.com/oauth2-proxy/oauth2-proxy/blob/master/README.md

Update `oauth2` Docker repository path

---

webviz_config/_deployment/azure_cli.py

Fix error description when dependencies are missing

---

setup.py
webviz_config/_deployment/azure_cli.py

Support latest `mypy` release

---

webviz_config/_config_parser.py

Similar update as in https://github.com/equinor/webviz-subsurface/pull/671.

Fix latest `mypy` warning

---

INTRODUCTION.md

Improve VSCode YAML schema installation documentation

---

webviz_config/generic_plugins/_data_table.py
webviz_config/generic_plugins/_table_plotter.py
webviz_config/utils/_localhost_open_browser.py

Closes #479.
Adds a couple of `pylint` `disable` due to what appears to be false positives (https://github.com/PyCQA/pylint/issues/4577).

Adjust according to new `pylint` warnings

---

.pylintrc

Similar to https://github.com/equinor/webviz-subsurface/issues/740

New `pylint` version

---

CHANGELOG.md
webviz_config/_deployment/radix.py
webviz_config/templates/Dockerfile.jinja2
webviz_config/templates/radixconfig.yaml.jinja2

Support Radix non-root and new blob driver

---

webviz_config/_deployment/radix_cli.py

Increase Radix build timeout

---

CONTRIBUTING.md

Updated `OAuth2` docs on how to retrieve access token

---

mypy.ini
webviz_config/__init__.py
webviz_config/_config_parser.py
webviz_config/_deployment/azure_cli.py
webviz_config/_docs/_build_docs.py
webviz_config/_localhost_token.py
webviz_config/generic_plugins/_markdown.py
webviz_config/plugins/__init__.py
webviz_config/plugins/_utils.py
webviz_config/themes/__init__.py
webviz_config/utils/_localhost_open_browser.py
webviz_config/utils/_silence_flask_startup.py

Closes #514. Related to https://github.com/Azure/azure-sdk-for-python/issues/20771.

Add new + remove obsolete type hint `mypy` instructions

---

CHANGELOG.md
webviz_config/_deployment/github_cli.py
webviz_config/_deployment/radix.py

Improve `git` steps of deployment

---

webviz_config/plugins/__init__.py

Remove `UserWarning` from `dash-bootstrap-components`

---

CHANGELOG.md
webviz_config/_user_data_dir.py

Change to `AppData` wrt. Windows 11

---

CHANGELOG.md
README.md
package-lock.json
package.json

Adjusted `npm postinstall` script for crossplatform. Added note to `README`.

Cross platform `package.json`

---

CHANGELOG.md
webviz_config/_deployment/github_cli.py

Avoid tempfile in `gh api` subprocess

---

package.json

Fix after #546. Also remove now unnecessary `mkdir`.
https://www.npmjs.com/package/copyfiles

Add `--flat` argument to `copyfiles`

---

CHANGELOG.md
webviz_config/static/README.md
webviz_config/templates/Dockerfile.jinja2

Document `ssh` deploy keys in Docker file

---

setup.py

Add `flask`/`werkzeug` as direct dependencies

---

CHANGELOG.md
setup.py
webviz_config/generic_plugins/_markdown.py

Add compatibility with `bleach >= 5`

---

setup.py

Related to https://github.com/equinor/webviz-config/issues/595.

Upper limit `flask-caching`

---

webviz_config/_deployment/azure_cli.py
webviz_config/_localhost_token.py
webviz_config/_plugin_abc.py
webviz_config/generic_plugins/_example_content_wrapper_plugin.py

Correct naming of override functions in example - callback functions were not called.

Fix example content wrapper plugin callback

---

tests/test_callback_typecheck.py
webviz_config/utils/_callback_typecheck.py

Error message does now include parameter, function and file names.

Improved `callback_typecheck` exception message

---

tests/test_callback_typecheck.py
webviz_config/utils/_callback_typecheck.py

Also adjusted tests in order to test for these cases.

Fixed issue with `Any`, empty `Dict`/`List` and `None` in `callback_typecheck`

---

mypy.ini
setup.py
webviz_config/_plugin_abc.py
webviz_config/webviz_store.py

Also added `implicit_optional=True` to `mypy.ini` (same as: https://github.com/equinor/webviz-subsurface/pull/1155)

Added pytest-forked to test requirements and updates for mypy 0.990

---

CHANGELOG.md
examples/basic_example.yaml
examples/example-markdown.md
webviz_config/generic_plugins/_markdown.py
webviz_config/templates/webviz_template.py.jinja2

Enable MathJax in `dcc.Markdown`

---

webviz_config/templates/copy_data_template.py.jinja2
webviz_config/templates/webviz_template.py.jinja2

Closes https://github.com/equinor/webviz-config/issues/660.

Ensure `SETTINGS_SUBSCRIPTIONS` is loaded before `webviz_settings`

---

CHANGELOG.md
examples/basic_example.yaml
webviz_config/_config_parser.py
webviz_config/_docs/_create_schema.py
webviz_config/_theme_class.py
webviz_config/templates/copy_data_template.py.jinja2
webviz_config/templates/webviz_template.py.jinja2

Expose plotly theme layout in config options

---

webviz_config/generic_plugins/_table_plotter.py

Fix tableplotter issue when using facet_col and undefined axis range
