examples/basic_example.yaml, examples/example-markdown.md, examples/example_markdown.md, setup.py, webviz_config/containers/__init__.py, webviz_config/containers/_markdown.py, webviz_config/static/assets/webviz_config.css, webviz_config/webviz_assets.py
=> Add markdown container

examples/example-markdown.md, webviz_config/containers/_markdown.py
Markdown by itself does not support height/width definition of images.
Resolves #34 by utilizing existing framework where `markdown` is parsed to `html` using a plugin to the [`python-markdown` library](https://github.com/Python-Markdown/markdown).
=> Add option for providing height/width of markdown images

webviz_config/_build_webviz.py, webviz_config/static/Dockerfile, webviz_config/static/README.md
Closes #33 
The docker building works well using the base image from dockerhub.
=> Simplify docker building process

webviz_config/themes/__init__.py, webviz_config/themes/_theme_class.py
Resolves #51.
In addition, change CSP `default-src` to `none` such that even e.g. `self` needs to be white-listed explicitly where needed.
=> Set CSP and FEATURE_POLICY on theme init

tests/test_data_table.py, tests/test_example_container.py, tests/test_syntax_highlighter.py, tests/test_table_plotter.py, webviz_config/templates/webviz_template.py.jinja2
With `dash~=1.0.0` [JS and CSS are by default served locally](https://github.com/plotly/dash/blob/master/dash/CHANGELOG.md#changed).
=> Remove obsolete dash settings

webviz_config/_write_script.py, webviz_config/command_line.py, webviz_config/templates/webviz_template.py.jinja2
Resolves #38. Also reduced the check time for `dash` to 1 second wrt. checking the generated app hash (default 3 seconds)
Now that hot reload in practice also works with `debug=False`, the `debug` argument flag can be removed.
=> Add hot reload

webviz_config/templates/webviz_template.py.jinja2
Resolves #65.
The log level is set at `WARNING`, which includes [`[WARNING, ERROR, CRITICAL]`](https://docs.python.org/3/library/logging.html#logging-levels).
=> Show errors and warnings in terminal

.travis.yml, README.md
Following the same changes as in https://github.com/equinor/webviz-subsurface-components/pull/12 when it comes to install now optional dash test dependencies.
In addition:
- Update chrome driver in `.travis.yml` (since Travis has jumped to Chrome version 76).
- Update to _Ubuntu Bionic 18.04_ (from default Travis Ubuntu Trusty 14.04) as that [is now the recommended way of using `xvfb` in Travis](https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-xvfb-to-run-tests-that-require-a-gui).
=> Update test dependency installation

setup.py, webviz_config/containers/_table_plotter.py
Plotly Express is now built-in to Plotly Python so there is no need to have it as a standalone dependency. 
https://medium.com/plotly/plotly-py-4-0-is-here-offline-only-express-first-displayable-anywhere-fc444e5659ee
=> Remove plotly express standalone dependency

CONTRIBUTING.md, webviz_config/containers/_example_container.py, webviz_config/containers/_table_plotter.py, webviz_config/webviz_assets.py
`pylint` does not recognize that decorated callback functions are used within `dash`, and therefore falsely reports them as unused. This is solved by prefixing them with `_`, which at the same time indicates that these callback functions are defined (and used) within the container.
=> Prefix callback functions

setup.py, webviz_config/containers/_table_plotter.py, webviz_config/themes/_theme_class.py
Follow-up of https://github.com/equinor/webviz-core-components/pull/12 on the `webviz-config` side. Responsibility for downloading and installing `plotly-cartesian` will be transferred to `webviz-core-components`.
=> Disallow eval in CSP

setup.py
📦 Need to add `requests` package as a direct dependency as long as https://github.com/plotly/dash-auth/issues/87 and the PR-solution https://github.com/plotly/dash-auth/pull/89 is not released on https://pypi.org/project/dash-auth/. 
Currently the built  [Dash docker base image](https://github.com/equinor/webviz-docker), built from `python:3.7-slim`, fails due to missing `requests` package. 💻
=> Add requests dependency

webviz_config/containers/_markdown.py
Depreciated, see [these lines ](https://github.com/Python-Markdown/markdown/blob/cb9cdc86575dab7afd3296c030e338cea3fc936e/markdown/util.py#L387-L392)in the python-markdown code for reference..
=> Remove depreciation warning for Markdown

examples/basic_example.yaml, examples/demo_portable.yaml, setup.py, webviz_config/__init__.py, webviz_config/_build_webviz.py, webviz_config/_config_parser.py, webviz_config/_is_reload_process.py, webviz_config/_localhost_open_browser.py, webviz_config/_localhost_token.py, webviz_config/_webviz_ott.py, webviz_config/_write_script.py, webviz_config/command_line.py, webviz_config/templates/webviz_template.py.jinja2
=> Use one-time-tokens and open browser automatically

webviz_config/containers/_container_class.py
As of [Python 3.3, `@abstractmethod` can correctly be combined with the `@property` decorator](https://docs.python.org/3.3/library/abc.html#abc.abstractproperty).
```python
class C(metaclass=ABCMeta):
@property
@abstractmethod
def my_abstract_property(self):
...
```
=> abstractmethod → abstractproperty

webviz_config/utils/terminal_colors.py
Before this PR, the ANSI sequences included an unnecessary and flashy _blinking effect_ (note that some terminal emulators ignore blink codes, so this is not always apparent).
=> Remove blinking text

setup.py, webviz_config/templates/webviz_template.py.jinja2
[Dash 1.7.0](https://github.com/plotly/dash/releases/tag/v1.7.0) includes the fix for `https://github.com/plotly/dash/pull/1027`.
It is no longer necessary to have a hidden dash_table in the initial rendered layout.
- Bump dash to 1.7
- Remove hidden table
- Also bump webviz-core-components
=> Use dash~=1.7. Remove hidden dash table

CONTRIBUTING.md, webviz_config/__init__.py, webviz_config/_config_parser.py, webviz_config/_shared_settings_subscriptions.py, webviz_config/_write_script.py, webviz_config/templates/copy_data_template.py.jinja2, webviz_config/templates/webviz_template.py.jinja2
Resolves #160.
Third-party containers can, in order to get rid of depreciation warning introduced here, do the following change:
Go from e.g.
```python
def __init__(self, app, container_settings, ...):
something = container_settings["something"]
...
```
to
```python
def __init__(self, app, ...):
something = app.webviz_settings["shared_settings"]["something"]
...
```
=> Support third-party containers checking shared_settings

webviz_config/webviz_store.py
Closes #93. Closes #166.
After this PR, all argument types should work in `webviz-store` (as long as they have a well behaving `__repr__` implementation). This is the same "limitation" as [`flask-caching`](https://github.com/sh4nks/flask-caching) has.
=> Support mutable objects in webviz-store

.travis.yml, README.md, setup.py
With release `0.16` of `pyarrow` from Apache, all dependencies now support Python 3.8. I.e. we can add 3.8 to the list of supported Python version, and at the same time require it to succeed in CI.
=> Support Python 3.8

README.md, webviz_config/_theme_class.py
There are use cases for using the full `plotly.js` plotting library (not only the cartesian `plotly.js` bundle like we currently use) - e.g. for visualizing parallel coordinates. However due to the open upstream `plotly.js` issue referenced in this PR, it requires `unsafe-eval` to be added to `script-src` while waiting for the upstream fix in `plotly.js`.
=> CSP change while waiting for upstream issue in plotly.js

.travis.yml, webviz_config/__init__.py, webviz_config/_user_data_dir.py, webviz_config/_user_preferences.py, webviz_config/certificate/__init__.py, webviz_config/certificate/_certificate_generator.py, webviz_config/certificate/_localhost_certificate.py, webviz_config/command_line.py, webviz_config/templates/webviz_template.py.jinja2, webviz_config/utils/__init__.py, webviz_config/utils/_localhost_open_browser.py
Solves #171.
E.g. the user can do things like
```
webviz preferences --browser firefox --theme equinor
```
to set Firefox as default browser, and not have to provide `--theme equinor` on each `webviz build` command.
=> Possibility to set preferred browser and theme

examples/basic_example.yaml, webviz_config/plugins/_example_portable.py, webviz_config/webviz_store.py
Example of bug related to default values in function arguments, related to: #158
=> Webvizstore default value error example

examples/demo_portable.yaml, examples/example_javascript.js, examples/example_stylesheet.css, webviz_config/plugins/_example_assets.py, webviz_config/templates/webviz_template.py.jinja2, webviz_config/webviz_assets.py
Resolves #207.
This PR makes the `WebvizAssets` behavior consistent between non-portable and portable runs, in the sense that plugin added JavaScript and CSS assets are loaded automatically by Dash in the browser (it already did for portable runs, but not for non-portable before this PR).
=> Load css and js assets automatically in non-portable mode

.github/workflows/webviz-config.yml
Since we now also, temporarily (waiting for removal of RHEL6 internally), have `pandas` version in the build matrix, we need to limit deploy of PyPI/GitHub pages also on pandas version in the build matrix.
=> Fix GitHub action workflow

webviz_config/plugins/_table_plotter.py, webviz_config/themes/default_assets/default_theme.css
Some minor fixes for TablePlotter:
- Use wcc.select for filters
- Make optional selectors (e.g. color, size) clearable
- Remove `y` variable from histogram
Also removed some css from default theme for wcc.select to work properly.
=> Improve selectors in TablePlotter

.github/workflows/webviz-config.yml
We can soon stop supporting `pandas==0.24.2`, which is the latest `pandas` version to support RHEL6. But for a few more months, we need to support it (but we will safely ignore the combination `python==3.8` and `pandas==0.24.2` in CI).
=> Skip python==3.8 and pandas<1.0 combination in CI

webviz_config/templates/webviz_template.py.jinja2
Dash by default prunes errors (omitting stack frames from Dash and Flask internals). Sometimes, user made plugins trigger errors only in Dash/Flask layer, resulting in _no errors/tracebacks_ printed to console, making debug difficult.
This PR turns off Dash's default error pruning.
=> Keep stack frames from Dash and Flask internals

.github/workflows/webviz-config.yml
Suddenly the existing way of getting `git` tag variable out of GitHub action workflow has started failing. The recommended practice appears to recently been changed, at the same time providing a cleaner way of getting the tag variable. Changing accordingly.
=> More robust GitHub action tag name

webviz_config/command_line.py
Resolves #254.
After this change, running `webviz` without any arguments returns (Python 3.6.9)
```bash
$ webviz
usage: Creates a Webviz Dash app from a configuration setup
[-h] SUBCOMMAND ...
Creates a Webviz Dash app from a configuration setup: error: the following arguments are required: SUBCOMMAND
```
```bash
$ webviz --help
usage: Creates a Webviz Dash app from a configuration setup
[-h] SUBCOMMAND ...
positional arguments:
SUBCOMMAND   Below are the available subcommands listed. Type e.g. 'webviz
build --help' to get help on one particular subcommand.
build      Build a Webviz Dash App
certificate
Create a https certificate authority for webviz (validity
limited to localhost only)
docs       Get documentation on installed Webviz plugins
preferences
Set preferred webviz settings …
```
=> Mark argparse subparser as required

CHANGELOG.md, tests/test_docstring.py, webviz_config/_docs/_build_docs.py, webviz_config/plugins/_markdown.py
Support for plugin docstrings that are indented to be used with `webviz docs` and `webviz schema`.
Also added an indent in `Markdown` plugin as the `black` indent in #270 had skipped the quoted section (this might be a risk going forward).
---
=> Allow indented plugin docstrings + Indent rest of markdown docstring

CHANGELOG.md, setup.py, webviz_config/_theme_class.py, webviz_config/templates/webviz_template.py.jinja2
Followup of https://github.com/plotly/dash/pull/1371. 
---
=> Support clientside callbacks in plugins

CHANGELOG.md, setup.py, webviz_config/__init__.py, webviz_config/_docs/_build_docs.py, webviz_config/plugins/__init__.py, webviz_config/themes/__init__.py
Change to more modern `importlib.metadata` wrt. `entrypoints` and version detection.
---
=> Change from pkg_resources to importlib

.github/workflows/webviz-config.yml
It is useful to be able to see e.g. `DeprecationWarning`s in the CI log.
This change will make sure we get all warnings (except those filtered away by code using e.g. `filterwarnings`).
=> Show all Python warnings in CI log

CHANGELOG.md, webviz_config/templates/copy_data_template.py.jinja2
Altered order of `WEBVIZ_ASSETS.make_portable` and `WEBVIZ_STORAGE.build_store` as the `WEBVIZ_ASSETS.make_portable` usually is much quicker, and would then fail faster if you are e.g. referring to a non-existing file. 
---
- ~~[ ] :robot: I have added tests, or extended existing tests, to cover any new features or bugs fixed in this PR.~~
=> Alter order of WEBVIZ_ASSETS and WEBVIZ_STORAGE

CHANGELOG.md, webviz_config/_build_webviz.py, webviz_config/_config_parser.py
=> Resolve UnclosedFile+ResourceWarning + graceful exit on KeyboardInterrupt

CHANGELOG.md, webviz_config/static/assets/webviz_layout.css
The menu still can "collapse" wrt. width if content is wide. Therefore adding a `min-width`.
Also, on small screens, the Dash provided `Tabs` have a break point at `800px`. We only want to specify menu width at screens larger than `800px` such that on small screens we utilize the available space.
=> min-width on menu + let menu expand on small screens

webviz_config/_build_webviz.py
Outdated error message (we call it _plugins_ today - not containers).
=> Update error message regarding exception in plugin

webviz_config/_plugin_abc.py
`io.BytesIO()` has a short hand for `seek(0) + read()`, which is `getvalue()`.
=> Use getvalue instead of seek+read

CHANGELOG.md, tests/test_portable.py, webviz_config/_config_parser.py, webviz_config/static/assets/webviz_layout.css, webviz_config/templates/webviz_template.py.jinja2
An attempt to replace current tab based page navigation with [dcc.Location](https://dash.plotly.com/urls).
- Components will require persistence as they are reloaded on page switching
- Initial load of app should be must faster, but page switching might be somewhat slower
=> Use urls instead of tabs for main layout

CHANGELOG.md, webviz_config/_theme_class.py
`plotly.js` "Download screenshot to png" requires `blob:` in `img-src` CSP.
---
=> Support plotly.js screenshot download

webviz_config/generic_plugins/_markdown.py
It appears that the latest version of `mypy` (released today) does not see the method `inlinePatterns` of `markdown.Markdown`, probably due to it being dynamically created or similarly within the `markdown` package.
=> Comply with latest version of mypy

setup.py
##hacktoberfestivus
Fixes relative links in the README.md in PyPi. The relative links are converted to the absolute ones, pointing at the relevant GitHub repo files, including commit information.
Contributors: The GreenTeam w/
torgeha
JoakimJohansen
antoneskov
---
=> Fix links on PyPI readme

CHANGELOG.md, setup.py, tests/test_plugin_metadata.py, webviz_config/_config_parser.py, webviz_config/_docs/_build_docs.py, webviz_config/plugins/__init__.py, webviz_config/templates/README.md.jinja2, webviz_config/templates/copy_data_template.py.jinja2, webviz_config/templates/webviz_template.py.jinja2, webviz_config/utils/_get_webviz_plugins.py
Closes #323.
This change enables us to automatically include plugin packages in Docker/cloud deployment, based on what the user have asked for in config.
Separately, it could also enable us to in plugin wrapper toolbar optionally later add buttons for link to plugin source/issue tracker, documentation...
=> Extract plugin distribution information on import

CHANGELOG.md, webviz_config/generic_plugins/_table_plotter.py
=> Pie chart plot type added to TablePlotter

CHANGELOG.md, webviz_config/templates/webviz_template.py.jinja2
After #230, generated app started using Dash `dcc.Location` and `dcc.Link` instead of tabs for multi-page apps. This enabled URL routing. At the same time, the root url `/` special case was set to show "Front page", however, users did not from before necessarily have a page called "Front page", as the "Front page" shown earlier was simply the first page in the list.
Change back to behavior prior to #230 - i.e. show first page in config as "Front page" and not rely on page title. We can revisit ideal wanted behaviour when solving #14 and deprecate config syntax accordingly.
=> Not rely on page called 'Front page'

.github/workflows/webviz-config.yml, CONTRIBUTING.md, README.md, setup.py
~As for now,~ this is a check of the new pip resolver. ~We will merge this when the new resolver actually becomes the default (in October, and with the release of `pip==20.3`).~
=> Use new pip resolver

CHANGELOG.md, webviz_config/_docs/_build_docs.py
Casting `pathlib.Path` to `str` when building docs to make it json-serializable
No tests added.
My editor is a bit keen on removing space at end of line, so a couple of lines it removed spaces in `CHANGELOG.md`
=> Cast pathlib.Path to str in docs to be json-serializable

.github/workflows/webviz-config.yml, CHANGELOG.md, setup.py
Pandas `0.24.2` not needed for internal deployment anymore, bumping to `pandas>=1.0`
---
=> Bump pandas to >=1.0

.github/workflows/webviz-config.yml
Pinning `pip==20.2.4` in CI due to [`black` install bug with `pip>=20.3`]( https://github.com/psf/black/issues/1847)
---
=> Pin pip to 20.2.4 due to bug in black install

CHANGELOG.md, webviz_config/_plugin_abc.py
The current way of importing TypedDict (for type hinting) using try-except seems to confuse mypy and causes errors during type checking. See for example in: https://github.com/equinor/webviz-subsurface/runs/1647251891?check_suite_focus=true
This PR fixes the issue by checking against Python version instead of using try-except during import.
See: 
https://mypy.readthedocs.io/en/stable/common_issues.html#python-version-and-system-platform-checks
and: 
https://github.com/python/typeshed/issues/3500#issuecomment-558398738
Also updated CHANGELOG to reflect the already published release 0.2.5
=> Fix for import of TypedDict for Python versions older than 3.8

CHANGELOG.md, CONTRIBUTING.md, tests/test_table_plotter.py, tests/unit_tests/test_webviz_settings.py, webviz_config/__init__.py, webviz_config/_config_parser.py, webviz_config/_webviz_settings_class.py, webviz_config/generic_plugins/_table_plotter.py, webviz_config/templates/copy_data_template.py.jinja2, webviz_config/templates/webviz_template.py.jinja2, webviz_config/utils/__init__.py, webviz_config/utils/_deprecate_webviz_settings_attribute_in_dash_app.py
Instead of piggybacking webviz_settings as an attribute onto the Dash application object, make (global) Webviz settings available to plugins through special argument `webviz_settings.` This argument is an instance of the `WebvizSettings` class.
This PR also deprecates access to webviz_settings as an attribute on the Dash application instance object that is currently being passed to the plugins as the special `app` argument. Also note that the new `WebvizSettings` class does not contain the `portable` attribute.
To start using the new scheme, and avoid the deprecated functionality, you will have to modify your plugin's `__init__()` function to include the special `webviz_settings` argument. E.g. change the signature from:
<pre>
def __init__(self, app: dash.Dash, csv_file: Path) -> None: …
=> Make special (global) webviz_settings argument available to plugins

webviz_config/generic_plugins/_markdown.py
`    webviz_config/generic_plugins/_markdown.py:37: error: Return type "Tuple[Any, ...]" of "handleMatch" incompatible with return type "Union[Tuple[Element, int, int], Tuple[None, None, None]]" in supertype "InlineProcessor"  [override]`
As I would have to import another package for the `Element` class + the new type hint would be very long. Seems like we are not anymore allowed a courser type hint (in this case `tuple`) than in parent classes you override.
Has limited user interest, so skipped it from `CHANGELOG`. Tell me if you disagree.
=> Fix MyPy 0.800 errors in Markdown plugin

.github/workflows/webviz-config.yml, CHANGELOG.md, CONTRIBUTING.md, setup.py, webviz_config/__init__.py, webviz_config/_localhost_token.py, webviz_config/_oauth2.py, webviz_config/templates/webviz_template.py.jinja2
=> Add oauth2 authorization code flow support

CHANGELOG.md, webviz_config/plugins/_utils.py
=> Skip multiple version of plugin warning if the metadata is equal

CHANGELOG.md, webviz_config/static/assets/webviz_layout.css
The height of the sidebar is such that a scrollbar is always shown on the web page.
Reducing the height a bit removes this and makes the layout cleaner.
---
=> Reduce height of sidebar to prevent overflow

setup.py
`black==19.*` and `black==20.*` have different styles. Ensure developers are using `black>=20`.
=> Add black lower version constraint

CONTRIBUTING.md
GitHub now renders TOC of `.md` files :arrow_right: remove inline TOC which is hard to maintain anyway. 
Also remove substring "configuration utility" in main title, as the content is equally valid for third-party plugin projects (not only `webviz-config`).
=> Remove TOC in CONTRIBUTING.md

CHANGELOG.md, webviz_config/_theme_class.py
See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/plugin-types.
The CSP directive `plugin-types` have been deprecated, and is not recommended anymore.
=> Remove deprecated 'plugin-types' CSP directive

CHANGELOG.md, webviz_config/_config_parser.py, webviz_config/deprecation_decorators.py
Moved `FutureWarnings` from `deprecated_decorators.py` to `_config_parser.py`.
Fixes #428.
=> Moved `FutureWarnings` for plugins

CHANGELOG.md, webviz_config/templates/copy_data_template.py.jinja2, webviz_config/templates/webviz_template.py.jinja2
Fixed the way global log level specified through the `--loglevel` command line argument is applied in awebviz application.
=> Fixed setting of global log level for webviz application

CHANGELOG.md, tests/test_docker_setup.py, tests/test_plugin_init.py, tests/test_plugin_metadata.py, webviz_config/_dockerize/_create_docker_setup.py, webviz_config/plugins/_utils.py
After this pull request, we increase the robustness of portable apps that are moved to cloud.
Before this PR we only ensured that the same version of `webviz-config` + all necessary plugin projects where the same, compared with what the user had installed when creating the portable app. After this PR we also ensure that sub-dependencies (direct+indirect) also have the same version in the generated Docker setup.
=> Add dependencies as plugin project metadata

webviz_config/templates/webviz_template.py.jinja2
Enforce the user specified global log level for the Dash app logger instead of always setting it to WARNING.
Remove the log handler that Dash insits on adding by default. This handler should not be needed since a handler gets added when we call `logging.basicConfig()` and we currently end up with two handlers for the Dash app logger.
Hardwire Dash application name to 'webviz_app' when creating the application object (instead of using `__name__`)
=> Adjusted Dash application logging to webviz's global logging mechanism.

webviz_config/templates/webviz_template.py.jinja2
Set Dash/Flask application name back to `__name__` after experiencing some problems when deploying with gunicorn.
=> Set Dash/Flask application name back to `__name__`

CHANGELOG.md, tests/unit_tests/test_webviz_factory_registry.py, webviz_config/templates/copy_data_template.py.jinja2, webviz_config/templates/webviz_template.py.jinja2, webviz_config/webviz_factory.py, webviz_config/webviz_factory_registry.py, webviz_config/webviz_instance_info.py
Added centralized/global `WebvizFactoryRegistry` that allows factories to be registered and shared between plugins. 
The class also facilitates storage of optional factory settings that are read from the YAML config file for later consumption when
an actual factory gets created and added to the registry.
The registry is merely managed and initialized by `webviz-config` and then exposed globally through `WEBVIZ_FACTORY_REGISTRY.`  Actual creation/registration of factories and subsequent retrival and use of factories will be done by the concrete factory classes and/or the plugins that utilize the factories. 
Note that currently, factory settings are not exposed publicly. Initial usage of these settings is assumed to be for experimental and internal tweaking purposes. The factory settings …
=> Added centralized factory registry for sharing factories between plugins

CHANGELOG.md, webviz_config/_config_parser.py
=> Suggest `webviz docs` if user gives incorrect configuration

webviz_config/_deployment/azure_cli.py
Ignore false positive from `pylint` after recent `astroid` release. It does not understand the object returned by `azure-cli` at runtime.
The `pylint` exception could probably be removed after #459.
=> Ignore false positive from `pylint`

webviz_config/deprecation_decorators.py
Changed callable signature type hint to be arbitrary in `@deprecated_plugin_arguments` signature.
=> Changed callable signature type hint to be arbitrary

webviz_config/static/assets/webviz_layout.css, webviz_config/themes/default_assets/default_theme.css
We don't need to support IE anymore. Therefore remove the 62.5% workaround (see https://css-tricks.com/css-font-size/ for a good read).
The menu width in `px` should with this change be the same as before in `rem` (assuming browser default font size of `16 px`):
```
16 px * (62.5 %) * (30 rem) = 300 px
```
=> Remove 62.5% CSS IE workaround

webviz_config/generic_plugins/_banner_image.py
The current non-camel case style names are giving warnings in console when running Dash in debug mode.
=> Use React camel case style names

webviz_config/templates/Dockerfile.jinja2, webviz_config/templates/radixconfig.yaml.jinja2
After testing with Radix and the Azure blob driver, it turns out we can also provide `uid` as input. Removing `group`.
=> Simplify Radix/Docker setup

.pylintrc, tests/test_plugin_init.py, webviz_config/_config_parser.py, webviz_config/_deployment/azure_cli.py, webviz_config/_deployment/radix.py, webviz_config/_docs/_build_docs.py, webviz_config/_plugin_abc.py, webviz_config/generic_plugins/_table_plotter.py, webviz_config/plugins/_utils.py, webviz_config/themes/__init__.py, webviz_config/themes/_default_theme.py
Enabling `useless-suppression` ensures we don't have unnecessary/obsolete `# pylint: disable=...` in the code base.
=> Add optional `pylint` option `useless-suppression`

CHANGELOG.md, webviz_config/_oauth2.py
If not setting a timezone, the timezone will be timezone naive. However, this will get serialized to a timezone-aware
timezone when being stored as a session object. This causes later comparisons to fail, since
we end up compariong timezone aware to timezone naive objects. Instead, always explicitly create timezone-aware datetimes
=> When comparing timezones, explicitly use UTC.

CHANGELOG.md, webviz_config/__main__.py
This will allow users to do `python -m webviz_config [...]` in addition to `webviz [...]`.
---
=> Add `__main__.py`

.github/workflows/webviz-config.yml, webviz_config/_deployment/azure_cli.py
Closes #512.
Also changed CI such that only of the tests in the matrix runs _without_ the extra dependencies being installed (in order to catch things like this).
This is a bug fix after a not-yet-released change :arrow_right: no changelog entry.
=> Fix undefined type annotation

CHANGELOG.md, tests/unit_tests/test_webviz_factory_registry.py, tests/unit_tests/test_webviz_instance_info.py, webviz_config/__init__.py, webviz_config/templates/copy_data_template.py.jinja2, webviz_config/templates/webviz_template.py.jinja2, webviz_config/webviz_factory_registry.py, webviz_config/webviz_instance_info.py
Added global `WebvizInstanceInfo` accessible through `WEBVIZ_INSTANCE_INFO.` 
An instance of `WebvizInstanceInfo` will be initialized/populated early on during a Webviz application's execution and can be accessed globally through `WEBVIZ_INSTANCE_INFO.` 
It has the following properties:
```
WebvizInstanceInfo.dash_app
WebvizInstanceInfo.run_mode
WebvizInstanceInfo.theme
WebvizInstanceInfo.storage_folder
```
Also marks `WebvizFactoryRegistry.app_instance_info` as deprecated
---
=> Added global `WebvizInstanceInfo`

.pylintrc, webviz_config/generic_plugins/_data_table.py, webviz_config/generic_plugins/_table_plotter.py
This centralizes the workaround in `.pylintrc` instead of `disables` necessary throughout the code base.
=> Workaround `pylint/astroid` bug

webviz_config/plugins/__init__.py
...since `dash-bootstrap-components` now have a release using the new `dash` import order (which ensures that the end user doesn't get `UserWarning`'s the user can't fix).
=> Remove `dash-bootstrap-components` `UserWarning` filter

CHANGELOG.md, webviz_config/generic_plugins/_banner_image.py, webviz_config/static/assets/webviz_config.css
Users can now specify if they want the image to be placed on the top or on the bottom of the BannerImage (center is the default). This is done by the css property `align-items`.
---
=> Implemented title option for BannerImage plugin

webviz_config/_localhost_token.py, webviz_config/webviz_factory_registry.py
Something upstream has become more intelligent, so we can remove a couple of `pylint` `disable`s.
=> Remove obsolete `pylint` disable

CHANGELOG.md, examples/basic_example_wlf.yaml, setup.py, webviz_config/generic_plugins/_example_wlf_plugin.py
This PR changes the file and plugin names from `ExampleContentWrapper` to `ExampleWlfPlugin`.
---
=> Changed plugin and file names

CONTRIBUTING.md, webviz_config/_localhost_token.py, webviz_config/_plugin_abc.py, webviz_config/generic_plugins/_banner_image.py, webviz_config/webviz_plugin_subclasses/_views.py
Download button not appearing for old plugin layout implementations.
- Fix breaking change
- Remove usage of unused prop from https://github.com/equinor/webviz-core-components/pull/232
- Ensure download button appearing and download callback being called for old layout implementation
----
Dependent on https://github.com/equinor/webviz-core-components/pull/232
=> Fix missing download button for old layout

webviz_config/_config_parser.py
This reverts one of the changes in #610, included in the latest prerelease.
Removing the `try/except` could become a breaking change, since some plugin projects are using subscripted type hints (and we do not support it yet - #199). Therefore, in order to not introduce a breaking change, we keep the `try/except` until #199 is done.
=> Reintroduce `try/except` `TypeError`

setup.py, tests/test_example_wlf_plugin.py, webviz_config/testing/_composite.py, webviz_config/testing/_plugin.py, webviz_config/testing/_webviz_ids.py
=> Webviz testing fixture

tests/test_callback_typecheck.py, webviz_config/generic_plugins/_example_wlf_plugin/_shared_settings/_shared_settings.py, webviz_config/generic_plugins/_example_wlf_plugin/_views/_plot/_view.py, webviz_config/generic_plugins/_example_wlf_plugin/_views/_table/_view.py, webviz_config/utils/__init__.py, webviz_config/utils/_callback_typecheck.py, webviz_config/webviz_plugin_subclasses/__init__.py
Improved `callback_typecheck` decorator (e.g. added conversion support of `TypedDict` and `Union`). Added a test for many different conversions and moved the decorator file to `utils`.
---
Closes #625.
Closes #622.
=> Improved `callback_typecheck` decorator, moved it and added test

tests/test_callback_typecheck.py, webviz_config/utils/_callback_typecheck.py
When converting a `Union` a first test was implemented before any conversion if an argument was already of the desired type. This test was implement by using the `isinstance` function. However, this check does not work with e.g. `typing.List` or `typing.Dict` types.
=> Added try except statement around `isinstance` check to avoid exception

webviz_config/generic_plugins/_example_wlf_plugin/_plugin.py, webviz_config/generic_plugins/_example_wlf_plugin/_views/_plot/__init__.py, webviz_config/generic_plugins/_example_wlf_plugin/_views/_plot/_view.py
Add color selection as view element settings for Plot. Add the settings group to tour steps.
To illustrate usage of view element setting and tour step dialog control.
Closes: https://github.com/equinor/webviz-config/issues/628
=> Add line color as view element setting for Plot in WLF example plugin

CHANGELOG.md, webviz_config/_config_parser.py, webviz_config/_docs/_create_schema.py, webviz_config/templates/webviz_template.py.jinja2
Now, it is possible to select which page to be shown first when opening a Webviz application via `options > menu > homepage` in the config file.
Dependent on https://github.com/equinor/webviz-core-components/pull/264.
=> Implemented new `homepage` option in `menu > options` in config file

tests/test_callback_typecheck.py, webviz_config/utils/_callback_typecheck.py
Introduced a new custom `_isinstance` function in `_callback_typecheck.py` in order to check if a variable already complies with the expected type. This does especially improve the type checking of `Union` types.
=> Improved typechecking, especially for `Union`

webviz_config/_config_parser.py
Webviz would not build when no `options` were given in config file. This was due to `homepage` property missing in fallback `options` dictionary.
=> Fixed issue when `options` not given in config file

CHANGELOG.md, tests/test_data_table.py, webviz_config/generic_plugins/_data_table.py, webviz_config/generic_plugins/_pivot_table.py
- Added to `PivotTable` in addition to `DataTable` in the original issue.
- _Only tested manually_
- Added to changelog
=> Added table download to `DataTable` and `PivotTable`

CHANGELOG.md, webviz_config/_theme_class.py
Allow `blob:` in `script-src` CSP in order to enable web worker usage in Dash components.
Computational heavy Dash components might want to use web workers. Since it is not easy in Dash to host related worker scripts, these worker scripts are typically created on demand and given as `blob:` URLs. We do not allow `data:` script URLs since they do not have the same security feature as `blob:` URLs which can only be by created by the browser itself and have scope limited to the windows it was created in.
=> Allow `blob:` in `script-src` CSP

CHANGELOG.md, webviz_config/command_line.py
Reduce time for running `webviz --help` by lazy importing top level entrypoints.
=> Lazy load modules in command line entrypoint

CHANGELOG.md, examples/basic_example.yaml, tests/test_table_plotter.py, webviz_config/generic_plugins/_table_plotter.py
Regression fix of https://github.com/equinor/webviz-config/pull/635
Tableplotter plugins using the `lock` arguments should still display any specified filters.
=> Regression fix: Show filters in TablePlotter when using `lock`

webviz_config/_oauth2.py
this is a hotfix for a security issue where silent token refresh asigns the wrong tokens to end users. A significant drawback of this hotfix is that it now forces an interactive token-retrieval every time tokens expire, which will cause the user to lose work in progress (unless state is set to persist)
---
- [x ] :tada: This PR closes #662.
=> Do not silently refresh tokens

.github/workflows/webviz-config.yml, README.md, tests/test_create_themed_layout.py, tests/test_data_table.py, tests/test_example_wlf_plugin.py, tests/test_portable.py, tests/test_syntax_highlighter.py, webviz_config/themes/__init__.py
=> py 3.11 3.12

.github/workflows/webviz-config.yml, CHANGELOG.md, webviz_config/_theme_class.py, webviz_config/templates/copy_data_template.py.jinja2, webviz_config/templates/webviz_template.py.jinja2, webviz_config/testing/_composite.py, webviz_config/testing/_webviz_ids.py
Enforcing React 18 in Dash and allowing `data:` in CSP `connect-src`.
=> Enforcing React 18 in Dash and allowing `data:` in CSP `connect-src`
